# Generated by Django 4.1.3 on 2022-11-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_useraccount_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="uuid",
            new_name="id",
        ),
    ]
