# Generated by Django 4.1.3 on 2022-12-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_uuid_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='student_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Student ID'),
        ),
    ]
