version: "3.9"

services:
  db:
    image: postgres:14-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db
    expose:
      - 5432
    env_file:
      - ./docker/env/.env.db.dev
    networks:
      - front_default

  app:
    build:
      context: .
      dockerfile: ./docker/DockerFile.local
    command: fab run
    volumes:
      - .:/var/www/api.aiu_booking.com/api/:z
    ports:
      - "7654:7654"
    env_file:
      - ./docker/env/.env.dev
    depends_on:
      - db
    networks:
        - front_default

volumes:
  postgres_data:

networks:
  front_default:
    external: true
