# Generated by Django 4.1.3 on 2022-11-27 12:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="facility",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2022,
                    11,
                    27,
                    12,
                    33,
                    5,
                    316917,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="Booking date",
            ),
        ),
    ]
