# Generated by Django 4.1.3 on 2022-11-27 12:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2022,
                    11,
                    27,
                    12,
                    31,
                    30,
                    507436,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="Booking date",
            ),
        ),
    ]
