# Generated by Django 4.1.3 on 2022-12-16 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, max_length=1048, null=True, verbose_name='Booking Title'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 18, 41, 36, 548585, tzinfo=datetime.timezone.utc), verbose_name='Booking date'),
        ),
    ]
