# Generated by Django 4.1.3 on 2022-12-18 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_title_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 18, 6, 43, 35, 175019, tzinfo=datetime.timezone.utc), verbose_name='Booking date'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.FileField(blank=True, default='facilities/default_facility.png', upload_to='facilities'),
        ),
    ]
